# Generated by Django 6.0.7 on 2026-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de l'utilisateur"),
        ),
    ]
