# Generated by Django 6.0.7 on 2026-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_utilisateur_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(default="Centre d'Intégration Scolaire et Professionnelle pour Aveugles et Malvoyants", help_text="Nom complet de l'établissement", max_length=255)),
                ('sigle', models.CharField(default='C.I.S.P.A.M.', help_text='Sigle ou acronyme', max_length=50)),
                ('ville', models.CharField(default='Bafoussam', help_text="Ville d'implantation", max_length=100)),
                ('boite_postale', models.CharField(blank=True, default='BP. 829 Bafoussam', help_text='Boîte postale complète', max_length=100)),
                ('telephone', models.CharField(blank=True, default='', help_text='Numéros de téléphone (séparés par des virgules)', max_length=100)),
                ('email', models.EmailField(blank=True, default='', help_text='Adresse email de contact', max_length=254)),
                ('logo', models.ImageField(blank=True, help_text="Logo officiel de l'établissement", null=True, upload_to='etablissement/logos/')),
            ],
            options={
                'verbose_name': 'Configuration Établissement',
                'verbose_name_plural': 'Configuration Établissement',
            },
        ),
    ]
