volumes:
  cispam_license_production_postgres_data: {}
  cispam_license_production_postgres_data_backups: {}
  cispam_license_production_redis_data: {}
  cispam_license_production_static: {}
  cispam_license_production_certbot_conf: {}
  cispam_license_production_certbot_www: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cispam_license_production_django
    volumes:
      - cispam_license_production_static:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    image: postgres:17-alpine
    volumes:
      - cispam_license_production_postgres_data:/var/lib/postgresql/data
      - cispam_license_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:7.2
    volumes:
      - cispam_license_production_redis_data:/data

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: cispam_license_production_nginx
    depends_on:
      - django
    volumes:
      - cispam_license_production_static:/app/staticfiles:ro
      - cispam_license_production_certbot_conf:/etc/letsencrypt
      - cispam_license_production_certbot_www:/var/www/certbot
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  certbot:
    image: certbot/certbot
    volumes:
      - cispam_license_production_certbot_conf:/etc/letsencrypt
      - cispam_license_production_certbot_www:/var/www/certbot
    entrypoint: >-
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait $${!}; done"
